// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MultiTenant.Data.Context;

#nullable disable

namespace MultiTenant.Data.Migrations.Log
{
    [DbContext(typeof(LogContext))]
    partial class LogContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MultiTenant.Model.Log", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Acontecimento")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("acontecimento");

                    b.Property<DateTime>("DataHora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValue(new DateTime(2022, 1, 6, 10, 54, 3, 471, DateTimeKind.Local).AddTicks(7320))
                        .HasColumnName("datahora");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("mensagem");

                    b.Property<string>("Schema")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("schema");

                    b.Property<string>("StackTrace")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("stack_trace");

                    b.HasKey("Id");

                    b.ToTable("logs", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
